import type { Coverage, Limitations, ReviewItem } from '../api';
import { formatLocalExport, formatUtc, permissionLabel, timeZone } from '../format';
import { PdfDoc } from './pdf';
import { APP_VERSION } from './evidence';

export type EvidencePackPayload = {
  header: {
    reviewId: string;
    name: string;
    scope: { type: string; ids: string[] };
    base: { seq: number; contentHash: string | null; startedAt?: number } | null;
    compare: { seq: number; contentHash: string | null; startedAt?: number } | null;
    signedBy: string | null;
    signedAt: number | null;
    signerTz: string | null;
    evidenceHash: string | null;
    signatureVersion: number;
    coverageHash: string | null;
    chainSeq?: number | null;
    prevReviewHash?: string | null;
    engineVersion: string;
    attestation: string | null;
    itemCount: number;
  };
  sections?: {
    methodology: { engineVersion: string; dataSources: string[]; note: string };
    limitations: Limitations;
    coverage: Coverage[];
    summary: Record<string, number>;
    controls: {
      version: number;
      mappings: Array<{ framework: string; id: string; title: string; accessRadar: string }>;
      disclaimer: string;
    };
    exceptions: Array<{
      itemKey: string;
      justification: string;
      expiresAt: number;
      status: string;
    }>;
    remediation: Array<{
      idx: number;
      itemKey: string;
      status: string;
      verifiedSeq: number | null;
    }>;
    audit: Array<{ at: number; actor: string; action: string }>;
  };
  items: Array<
    Pick<
      ReviewItem,
      | 'itemKey'
      | 'subjectType'
      | 'subjectId'
      | 'permissions'
      | 'decision'
      | 'note'
      | 'expiresAt'
      | 'change'
      | 'projectId'
      | 'groupId'
    >
  >;
  nextPage?: number | null;
  page?: number;
  pageSize?: number;
};

/** Builds the Advanced evidence-pack PDF from one or more getEvidencePack pages. */
export async function evidencePackPdf(
  pack: EvidencePackPayload,
  allItems: EvidencePackPayload['items'],
  ctx: { siteUrl?: string; tz?: string } = {},
): Promise<Uint8Array> {
  const h = pack.header;
  const s = pack.sections;
  const tz = h.signerTz || ctx.tz || timeZone();
  const doc = new PdfDoc(`AccessRadar evidence pack - ${h.name}`);
  doc.title(h.name, 'AccessRadar evidence pack (Advanced)');
  doc.keyValues([
    ['Generated by', `AccessRadar ${APP_VERSION}`],
    ['Site', ctx.siteUrl ?? ''],
    ['Review ID', h.reviewId],
    ['Scope', `${h.scope.type}${h.scope.ids.length ? `: ${h.scope.ids.join(', ')}` : ''}`],
    [
      'Base snapshot',
      h.base
        ? `#${h.base.seq} · ${formatUtc(h.base.startedAt ?? null)} · hash ${h.base.contentHash ?? '—'}`
        : '—',
    ],
    [
      'Compare snapshot',
      h.compare ? `#${h.compare.seq} · hash ${h.compare.contentHash ?? '—'}` : '—',
    ],
    ['Signed by', h.signedBy ?? ''],
    [
      'Signed at',
      h.signedAt ? `${formatUtc(h.signedAt)} / ${formatLocalExport(h.signedAt, tz)}` : '',
    ],
    ['Evidence hash', h.evidenceHash ?? ''],
    ['Chain #', h.chainSeq != null ? String(h.chainSeq) : 'pre-chain'],
    ['Previous hash', h.prevReviewHash ?? ''],
    ['Signature version', String(h.signatureVersion)],
    ['Coverage hash', h.coverageHash ?? ''],
    ['Engine', h.engineVersion],
  ]);
  if (h.attestation) {
    doc.heading('Attestation');
    doc.paragraph(`"${h.attestation}"`);
  }
  doc.heading('How to verify');
  doc.paragraph(
    'Recompute SHA-256 over the canonical evidence document (signature version above). In AccessRadar: Reviews → Verify. Deep check recomputes the snapshot content hash from facts.',
  );

  if (s) {
    doc.heading('Methodology');
    doc.paragraph(s.methodology.note);
    doc.paragraph(`Engine ${s.methodology.engineVersion}. Read-only Jira REST sources:`);
    s.methodology.dataSources.forEach((d) => doc.paragraph(`• ${d}`, 9, 0.15));

    doc.heading('Coverage & limitations');
    doc.paragraph(`Completeness: ${s.limitations.label} (limitations v${s.limitations.version}).`);
    s.limitations.statements.forEach((t) => doc.paragraph(`• ${t}`, 9, 0.15));
    if (s.coverage.length) {
      doc.table(
        [
          { header: 'Status', width: 1.2 },
          { header: 'Area', width: 1.8 },
          { header: 'Target', width: 1.5 },
          { header: 'Reason', width: 4 },
        ],
        s.coverage.map((c) => [c.status, c.area, c.target, c.reason]),
        7.5,
      );
    }

    doc.heading('Summary');
    doc.keyValues(Object.entries(s.summary).map(([k, v]) => [k, String(v)]));

    doc.heading('Control mapping');
    doc.paragraph(`Mapping version ${s.controls.version}. ${s.controls.disclaimer}`);
    doc.table(
      [
        { header: 'Framework', width: 1.6 },
        { header: 'ID', width: 0.9 },
        { header: 'Title', width: 2.2 },
        { header: 'AccessRadar', width: 3.8 },
      ],
      s.controls.mappings.map((m) => [m.framework, m.id, m.title, m.accessRadar]),
      7.5,
    );

    doc.heading('Exceptions (scope-relevant)');
    if (!s.exceptions.length) doc.paragraph('None.');
    else
      doc.table(
        [
          { header: 'Item', width: 2.5 },
          { header: 'Status', width: 1.2 },
          { header: 'Expires', width: 2 },
          { header: 'Justification', width: 3 },
        ],
        s.exceptions.map((e) => [e.itemKey, e.status, formatUtc(e.expiresAt), e.justification]),
        7.5,
      );

    doc.heading('Remediation');
    if (!s.remediation.length) doc.paragraph('No revocations tracked.');
    else
      doc.table(
        [
          { header: 'Item', width: 3.5 },
          { header: 'Status', width: 1.8 },
          { header: 'Verified seq', width: 1.5 },
        ],
        s.remediation.map((r) => [
          r.itemKey,
          r.status,
          r.verifiedSeq != null ? String(r.verifiedSeq) : '—',
        ]),
        7.5,
      );

    doc.heading('Audit trail (excerpt)');
    if (!s.audit.length) doc.paragraph('No events.');
    else
      doc.table(
        [
          { header: 'When (UTC)', width: 2.2 },
          { header: 'Actor', width: 2 },
          { header: 'Action', width: 3.5 },
        ],
        s.audit.map((a) => [formatUtc(a.at), a.actor, a.action]),
        7.5,
      );
  }

  doc.heading('Decisions');
  doc.table(
    [
      { header: 'Item', width: 2.2 },
      { header: 'Decision', width: 1.1 },
      { header: 'Access', width: 1.8 },
      { header: 'Note', width: 2.2 },
      { header: 'Expires', width: 1.4 },
    ],
    allItems.map((i) => [
      i.itemKey,
      i.decision ?? 'undecided',
      i.permissions.map(permissionLabel).join(', '),
      i.note ?? '',
      i.expiresAt ? formatUtc(i.expiresAt) : '',
    ]),
    7.5,
  );
  return doc.toBytes();
}

export const evidencePackFileName = (name: string, id: string) =>
  `accessradar_evidence_pack_${name.replace(/[^a-z0-9]+/gi, '_').slice(0, 40)}_${id.slice(0, 8)}.pdf`;
