import type { Changes, Coverage, Limitations, ReviewDetail, Snapshot } from '../api';
import { formatLocalExport, formatUtc, permissionLabel, slug, timeZone } from '../format';
import { csvCell, toCsv } from './csv';
import { PdfDoc } from './pdf';

export const APP_VERSION = '1.0.0';

export interface ExportContext {
  siteUrl?: string;
  exportedBy?: string;
  now?: number;
  tz?: string;
}

const both = (ms: number | null | undefined, tz: string) =>
  ms ? `${formatUtc(ms)} / ${formatLocalExport(ms, tz)}` : '';

function baseMeta(ctx: ExportContext, extra: Array<[string, string]>): Array<[string, string]> {
  const now = ctx.now ?? Date.now();
  return [
    ['Generated by', `AccessRadar ${APP_VERSION} (read-only, Runs on Atlassian)`],
    ...(ctx.siteUrl ? ([['Site', ctx.siteUrl]] as Array<[string, string]>) : []),
    ['Exported at', both(now, ctx.tz ?? timeZone())],
    ...extra,
  ];
}

const METHODOLOGY = [
  'Effective access is computed from the snapshot: permission scheme grants, project role actors, group membership and application access.',
  'Expanded holder types: project role, group, named user, project lead, application role. Issue-dependent holders (reporter, assignee, user/group custom fields) are listed as conditional and never expanded to people. "Anyone" grants are anonymous access.',
  'Limitations: Jira has no API listing global permission holders, so admin access is derived from groups with admin/site-admin access (partial). Team-managed projects use their own per-project scheme and roles. Groups whose members could not be read are listed as such.',
  'AccessRadar supports evidence collection. It is not a certification or a guarantee of compliance. Hashes are tamper-evident, not tamper-proof.',
];

function coverageRows(coverage: Coverage[]) {
  return coverage.map((c) => [c.status, c.area.replace(/-/g, ' '), c.target, c.reason]);
}

/** Shared preamble for CSV exports (UI/PDF/CSV use the same limitations text). */
export function coverageLimitationsPreamble(
  coverage: Coverage[],
  limitations?: Limitations | null,
): string[] {
  const lines: string[] = [];
  if (limitations) {
    lines.push(`# limitations_version: ${limitations.version}`);
    lines.push(`# completeness: ${limitations.label}`);
    for (const s of limitations.statements) lines.push(`# limitation: ${s}`);
  }
  for (const c of coverage) {
    lines.push(
      `# coverage,${csvCell(c.status)},${csvCell(c.area)},${csvCell(c.target)},${csvCell(c.reason)}`,
    );
  }
  return lines;
}

export function coverageOnlyCsv(
  coverage: Coverage[],
  limitations?: Limitations | null,
  ctx: ExportContext = {},
): string {
  const meta = baseMeta(ctx, [
    ['Section', 'Coverage'],
    ...(limitations
      ? ([
          ['Limitations version', String(limitations.version)],
          ['Completeness', limitations.label],
        ] as Array<[string, string]>)
      : []),
  ]);
  const rows = coverage.map((c) => ({
    status: c.status,
    area: c.area,
    target: c.target,
    reason: c.reason,
  }));
  return toCsv(['status', 'area', 'target', 'reason'], rows, {
    meta,
    preamble: limitations?.statements.map((s) => `# limitation: ${s}`) ?? [],
  });
}

function writeLimitationsPdf(doc: PdfDoc, coverage: Coverage[], limitations?: Limitations | null) {
  doc.heading('Coverage & limitations');
  if (limitations) {
    doc.paragraph(
      `Completeness: ${limitations.label}. Limitations version ${limitations.version}.`,
      9,
      0.2,
    );
    for (const s of limitations.statements) doc.paragraph(`• ${s}`, 9, 0.15);
  }
  doc.table(
    [
      { header: 'Status', width: 1 },
      { header: 'Area', width: 1.4 },
      { header: 'Target', width: 1.4 },
      { header: 'Detail', width: 4 },
    ],
    coverageRows(coverage),
  );
}

// ---------- snapshot: access matrix ----------
export const MATRIX_COLUMNS = [
  'snapshot_id',
  'captured_at_utc',
  'project_key',
  'project_name',
  'project_style',
  'subject_type',
  'subject_id',
  'display_name',
  'account_type',
  'active',
  'permission',
  'path',
  'path_codes',
  'completeness_flag',
];

export function matrixCsv(
  snapshot: Snapshot,
  rows: Array<Record<string, string>>,
  ctx: ExportContext = {},
  risks: Array<{
    id: string;
    severity: string;
    title: string;
    count: number;
    partial?: boolean;
  }> = [],
  coverage: Coverage[] = [],
  limitations?: Limitations | null,
) {
  const meta = baseMeta(ctx, [
    ['Snapshot', `#${snapshot.seq} (${snapshot.status})`],
    ['Captured at', both(snapshot.startedAt, ctx.tz ?? timeZone())],
    ['Engine version', snapshot.engineVersion],
    ['Snapshot content hash (SHA-256)', snapshot.contentHash ?? ''],
  ]);
  const enriched = rows.map((r) => ({
    ...r,
    snapshot_id: snapshot.seq,
    captured_at_utc: formatUtc(snapshot.startedAt),
  }));
  let out = toCsv(MATRIX_COLUMNS, enriched, {
    meta,
    preamble: coverageLimitationsPreamble(coverage, limitations),
  });
  if (risks.length) {
    const riskRows = risks.map((r) => ({
      risk_id: r.id,
      severity: r.severity,
      title: r.title,
      count: r.count,
      partial: r.partial ? 'yes' : 'no',
    }));
    out +=
      '\r\n' +
      toCsv(['risk_id', 'severity', 'title', 'count', 'partial'], riskRows, {
        meta: [['Section', 'Risks']],
        bom: false,
      });
  }
  return out;
}

export async function matrixPdf(
  snapshot: Snapshot,
  coverage: Coverage[],
  rows: Array<Record<string, string>>,
  ctx: ExportContext = {},
  limitations?: Limitations | null,
) {
  const tz = ctx.tz ?? timeZone();
  const doc = new PdfDoc(`AccessRadar access matrix - snapshot #${snapshot.seq}`);
  doc.title(`Access matrix, snapshot #${snapshot.seq}`, 'Who has access to what in Jira, and why');
  doc.keyValues(
    baseMeta(ctx, [
      ['Captured at', both(snapshot.startedAt, tz)],
      ['Status', snapshot.status],
      ['Engine version', snapshot.engineVersion],
      ['Content hash (SHA-256)', snapshot.contentHash ?? ''],
      ['Entries', String(rows.length)],
    ]),
  );
  doc.heading('Methodology');
  METHODOLOGY.forEach((p) => doc.paragraph(p));
  writeLimitationsPdf(doc, coverage, limitations);
  doc.heading('Access');
  doc.table(
    [
      { header: 'Project', width: 1 },
      { header: 'Who', width: 2 },
      { header: 'Permission', width: 1.6 },
      { header: 'Why (path)', width: 4.4 },
    ],
    rows.map((r) => [
      r.project_key,
      `${r.display_name}${r.active === 'no' ? ' (inactive)' : ''}`,
      permissionLabel(r.permission),
      r.path,
    ]),
    7.5,
  );
  return doc.toBytes();
}

export const matrixFileName = (s: Snapshot, ext: string) =>
  `accessradar_access_matrix_snapshot-${s.seq}.${ext}`;

// ---------- changes between snapshots ----------
export const CHANGES_COLUMNS = [
  'change',
  'fact_type',
  'project_key',
  'subject_type',
  'subject_id',
  'display_name',
  'permission',
  'detail',
  'path',
  'snapshot_a',
  'snapshot_b',
];

export function changesRows(c: Changes) {
  const a = c.a?.seq ?? '';
  const b = c.b?.seq ?? '';
  return [
    ...c.granted.map((t) => ({
      change: 'granted',
      fact_type: 'effective_access',
      project_key: t.project.key,
      subject_type: t.subject.type,
      subject_id: t.subject.id,
      display_name: t.subject.name,
      permission: t.permission,
      detail: 'Access granted',
      path: t.reasons.join(' | '),
      snapshot_a: a,
      snapshot_b: b,
    })),
    ...c.revoked.map((t) => ({
      change: 'revoked',
      fact_type: 'effective_access',
      project_key: t.project.key,
      subject_type: t.subject.type,
      subject_id: t.subject.id,
      display_name: t.subject.name,
      permission: t.permission,
      detail: 'Access revoked',
      path: t.reasons.join(' | '),
      snapshot_a: a,
      snapshot_b: b,
    })),
    ...c.facts.map((f) => ({
      change: f.change,
      fact_type: f.kind,
      project_key: '',
      subject_type: '',
      subject_id: '',
      display_name: f.label,
      permission: f.permission ?? '',
      detail: f.detail,
      path: '',
      snapshot_a: a,
      snapshot_b: b,
    })),
  ];
}

export function changesCsv(c: Changes, ctx: ExportContext = {}) {
  const tz = ctx.tz ?? timeZone();
  return toCsv(CHANGES_COLUMNS, changesRows(c), {
    meta: baseMeta(ctx, [
      [
        'Snapshot A',
        c.a ? `#${c.a.seq} ${both(c.a.startedAt, tz)} hash ${c.a.contentHash ?? ''}` : '',
      ],
      [
        'Snapshot B',
        c.b ? `#${c.b.seq} ${both(c.b.startedAt, tz)} hash ${c.b.contentHash ?? ''}` : '',
      ],
    ]),
  });
}

export async function changesPdf(c: Changes, ctx: ExportContext = {}) {
  const tz = ctx.tz ?? timeZone();
  const doc = new PdfDoc(`AccessRadar changes #${c.a?.seq} -> #${c.b?.seq}`);
  doc.title(
    `Access changes, snapshot #${c.a?.seq} to #${c.b?.seq}`,
    'Access granted and revoked between two snapshots',
  );
  doc.keyValues(
    baseMeta(ctx, [
      ['Snapshot A', c.a ? `#${c.a.seq}, ${both(c.a.startedAt, tz)}` : ''],
      ['Snapshot A hash', c.a?.contentHash ?? ''],
      ['Snapshot B', c.b ? `#${c.b.seq}, ${both(c.b.startedAt, tz)}` : ''],
      ['Snapshot B hash', c.b?.contentHash ?? ''],
      ['Key permissions', c.keyPermissions.map(permissionLabel).join(', ')],
      [
        'Summary',
        `${c.granted.length} granted, ${c.revoked.length} revoked, ${c.facts.length} configuration changes`,
      ],
    ]),
  );
  const accessCols = [
    { header: 'Project', width: 1 },
    { header: 'Who', width: 2 },
    { header: 'Permission', width: 1.6 },
    { header: 'Why (path)', width: 4.4 },
  ];
  doc.heading('Access granted');
  doc.table(
    accessCols,
    c.granted.map((t) => [
      t.project.key,
      t.subject.name,
      permissionLabel(t.permission),
      t.reasons.join(' | '),
    ]),
  );
  doc.heading('Access revoked');
  doc.table(
    accessCols,
    c.revoked.map((t) => [
      t.project.key,
      t.subject.name,
      permissionLabel(t.permission),
      t.reasons.join(' | '),
    ]),
  );
  doc.heading('Configuration changes');
  doc.table(
    [
      { header: 'Change', width: 1 },
      { header: 'Area', width: 1.2 },
      { header: 'What', width: 3.5 },
      { header: 'Detail', width: 3.3 },
    ],
    c.facts.map((f) => [f.change, f.category, f.label, f.detail]),
  );
  return doc.toBytes();
}

export const changesFileName = (c: Changes, ext: string) =>
  `accessradar_changes_${c.a?.seq ?? 'x'}_${c.b?.seq ?? 'y'}.${ext}`;

// ---------- review decisions + evidence pack ----------
export const REVIEW_COLUMNS = [
  'review_id',
  'item',
  'project_key',
  'group',
  'subject_type',
  'subject_id',
  'display_name',
  'permissions',
  'path',
  'path_codes',
  'change',
  'decision',
  'note',
  'expires_at_utc',
  'expires_at_local',
  'decided_by',
  'decided_at_utc',
  'decided_at_local',
];

const DECISION = {
  keep: 'keep',
  revoke: 'revoke (to do in Jira)',
  exception: 'exception',
} as const;

export function reviewRows(d: ReviewDetail, tz = timeZone()) {
  return d.items.map((i) => ({
    review_id: d.review.id,
    item: i.itemKey,
    project_key: i.project?.key ?? '',
    group: i.groupName ?? '',
    subject_type: i.subjectType,
    subject_id: i.subjectId,
    display_name: i.subject.name,
    permissions: i.permissions.join(' '),
    path: i.reasons.join(' | '),
    path_codes: i.pathCodes.join(' | '),
    change: i.change ?? '',
    decision: i.decision ? DECISION[i.decision] : '',
    note: i.note ?? '',
    expires_at_utc: formatUtc(i.expiresAt ?? null),
    expires_at_local: formatLocalExport(i.expiresAt ?? null, tz),
    decided_by: i.decidedBy ?? '',
    decided_at_utc: formatUtc(i.decidedAt),
    decided_at_local: formatLocalExport(i.decidedAt, tz),
  }));
}

function reviewMeta(d: ReviewDetail, ctx: ExportContext): Array<[string, string]> {
  const r = d.review;
  const signerTz = r.signerTz ?? ctx.tz ?? timeZone();
  return baseMeta(ctx, [
    ['Review', r.name],
    ['Review ID', r.id],
    [
      'Status',
      r.status === 'signed'
        ? 'Signed (read-only)'
        : r.status === 'in_progress'
          ? 'In progress (not signed)'
          : 'Draft (not signed)',
    ],
    [
      'Scope',
      r.scope.type === 'site' ? 'Whole site' : `${r.scope.type}: ${r.scopeLabels.join(', ')}`,
    ],
    [
      'Base snapshot',
      d.base ? `#${d.base.seq}, ${both(d.base.startedAt, signerTz)}` : `#${r.baseSeq}`,
    ],
    ['Base snapshot hash', d.base?.contentHash ?? ''],
    [
      'Comparison snapshot',
      d.compare ? `#${d.compare.seq}, ${both(d.compare.startedAt, signerTz)}` : 'none',
    ],
    ['Key permissions', r.keyPermissions.map(permissionLabel).join(', ')],
    ['Engine version', r.engineVersion],
    ['Signed by', r.signedBy ? `${r.signedByName ?? ''} (accountId ${r.signedBy})` : 'not signed'],
    [
      'Signed at',
      r.signedAt ? `${formatUtc(r.signedAt)} / ${formatLocalExport(r.signedAt, signerTz)}` : '',
    ],
    ['Evidence hash (SHA-256)', r.evidenceHash ?? 'not signed'],
    [
      'Chain #',
      r.status === 'signed' ? (r.chainSeq != null ? String(r.chainSeq) : 'pre-chain') : '',
    ],
    ['Previous hash', r.prevReviewHash ?? ''],
    ['Signature version', r.status === 'signed' ? String(r.signatureVersion ?? 1) : ''],
  ]);
}

export function reviewCsv(d: ReviewDetail, ctx: ExportContext = {}) {
  return toCsv(REVIEW_COLUMNS, reviewRows(d, d.review.signerTz ?? ctx.tz ?? timeZone()), {
    meta: reviewMeta(d, ctx),
    preamble: coverageLimitationsPreamble(d.coverage, d.limitations),
  });
}

export async function reviewPdf(d: ReviewDetail, ctx: ExportContext = {}) {
  const r = d.review;
  const items = d.items.filter((i) => i.change !== 'removed');
  const flagged = items.filter((i) => i.decision === 'revoke');
  const kept = items.filter((i) => i.decision === 'keep');
  const exceptions = items.filter((i) => i.decision === 'exception');
  const doc = new PdfDoc(`AccessRadar evidence pack - ${r.name}`);
  doc.title(r.name, 'Jira access review, evidence pack');
  doc.keyValues(reviewMeta(d, ctx));
  if (r.attestation) {
    doc.heading('Attestation');
    doc.paragraph(`"${r.attestation}"`);
  }
  doc.heading('Methodology');
  METHODOLOGY.forEach((p) => doc.paragraph(p));
  doc.paragraph(
    'To verify: recompute SHA-256 over the canonical review document (review, items and decisions keyed by accountId, base snapshot hash, engine version, signer and sign-off time). AccessRadar can re-verify it in the app (Reviews > Verify).',
    9,
    0.3,
  );
  writeLimitationsPdf(doc, d.coverage, d.limitations);
  doc.heading('Summary');
  doc.keyValues([
    ['Items reviewed', String(items.length)],
    ['Keep', String(kept.length)],
    ['Revoke (to do in Jira)', String(flagged.length)],
    ['Exception', String(exceptions.length)],
    ['Undecided', String(items.length - kept.length - flagged.length - exceptions.length)],
    ['New since comparison', String(items.filter((i) => i.change === 'new').length)],
    ['Removed since comparison', String(d.items.filter((i) => i.change === 'removed').length)],
  ]);
  doc.heading('Revocations to perform in Jira');
  doc.paragraph(
    'AccessRadar never changes Jira. These items were flagged by the reviewer and must be removed manually.',
    9,
    0.3,
  );
  const cols = [
    { header: 'Scope', width: 1.1 },
    { header: 'Who', width: 1.8 },
    { header: 'Access', width: 1.6 },
    { header: 'Why (path)', width: 3 },
    { header: 'Note', width: 1.8 },
  ];
  const row = (i: (typeof items)[number]) => [
    i.project?.key ?? i.groupName ?? '',
    i.subject.name,
    i.permissions.map(permissionLabel).join(', '),
    i.reasons.join(' | '),
    i.note ?? '',
  ];
  doc.table(cols, flagged.map(row));
  doc.heading('All decisions');
  doc.table(
    [
      ...cols.slice(0, 3),
      { header: 'Decision', width: 1 },
      { header: 'Decided by / at (UTC)', width: 2 },
      { header: 'Note', width: 1.8 },
    ],
    items.map((i) => [
      i.project?.key ?? i.groupName ?? '',
      i.subject.name,
      i.permissions.map(permissionLabel).join(', '),
      i.decision ?? 'undecided',
      `${i.decidedByName ?? ''} ${formatUtc(i.decidedAt)}`.trim(),
      i.note ?? '',
    ]),
    7.5,
  );
  return doc.toBytes();
}

export const reviewFileName = (d: ReviewDetail, ext: string) =>
  `accessradar_review_${slug(d.review.name)}_${d.review.id.slice(0, 8)}.${ext}`;
